algoritmo "somaFuncao"
// Função : Soma em Funcao
// Autor : Evolua Sumare
// Data : 26/03/2020
var
    V1, V2: inteiro
    s: inteiro
funcao   soma(x,y: inteiro): inteiro
inicio
      retorne x+y
fimfuncao



inicio
    escreva("Digite primeiro valor: ")
    leia(v1)
    escreva("Digite segundo valor: ")
    leia(v2)
    S <- soma(v1, v2)
    escreval("A soma entre ", v1, " e ", v2, " é igual à ", s)



fimalgoritmo
