algoritmo "contadorRepeticao"
// Função :  Contador Estrutura de Repetição
// Autor :  Evolua Sumaré
// Data : 26/03/2020
var
   valor, contador : inteiro
inicio
   contador <- 0
   escreval("Quer contar até quanto? ")
   leia (valor)
      enquanto (contador <= valor) faca
            escreval (contador)
            contador <- contador + 1
   fimenquanto
   escreval ("Terminei de contar! ")
fimalgoritmo
